import Profile1 from "./assets/photo (1).jpg";
import Profile2 from "./assets/photo (2).jpg";
import Profile3 from "./assets/photo (3).jpg";
import Profile4 from "./assets/photo (4).jpg";
import Profile5 from "./assets/photo (5).jpg";
import Profile6 from "./assets/photo (6).jpg";
import Profile from "./assets/photo (8).jpg";

export const Notification = [
  {
    id: 1,
    profile_img: Profile1,
    user: "Thakur Singh",
    activity:
      "accepted your friend request. Connected a social account: Google",
    time: "2 DAYS AGO",
  },
  {
    id: 2,
    profile_img: Profile2,
    user: "Thakur Singh",
    activity: "accepted your friend request Connected a social account: Google",
    time: "2 DAYS AGO",
  },
  {
    id: 3,
    profile_img: Profile3,
    user: "Thakur Singh",
    activity: "accepted your friend request Connected a social account: Google",
    time: "2 DAYS AGO",
  },
  {
    id: 4,
    profile_img: Profile4,
    user: "Thakur Singh",
    activity: "accepted your friend request Connected a social account: Google",
    time: "2 DAYS AGO",
  },
  {
    id: 5,
    profile_img: Profile5,
    user: "Thakur Singh",
    activity: "accepted your friend request Connected a social account: Google",
    time: "2 DAYS AGO",
  },
  {
    id: 6,
    profile_img: Profile6,
    user: "Ankit Singh",
    activity: "accepted your friend request Connected a social account: Google",
    time: "2 DAYS AGO",
  },
  {
    id: 7,
    profile_img: Profile1,
    user: "Thakur Singh",
    activity: "accepted your friend request Connected a social account: Google",
    time: "2 DAYS AGO",
  },
  {
    id: 8,
    profile_img: Profile1,
    user: "Thakur Singh",
    activity: "accepted your friend request Connected a social account: Google",
    time: "2 DAYS AGO",
  },
];

export const messege = [
  {
    id: 1,
    profile_img: Profile,
    user: "Romi Singh",
    sms: "good morning",
  },
  {
    id: 2,
    profile_img: Profile,
    user: "Ankur",
    sms: "jaldi aa bhai",
  },
  {
    id: 3,
    profile_img: Profile,
    user: "Romi Singh",
    sms: "good morning",
  },
  {
    id: 4,
    profile_img: Profile,
    user: "Mukesh",
    sms: "aaj ghumne jate h khi",
  },
  {
    id: 5,
    profile_img: Profile,
    user: "Ankit Singh",
    sms: "soja bhai",
  },
];

export const post = [
  {
    id: 1,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 20 MIN AGO",
    post: Profile3,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },

  {
    id: 2,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 15 MIN AGO",
    post: Profile1,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },
  {
    id: 3,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 15 MIN AGO",
    post: Profile2,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },
  {
    id: 4,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 15 MIN AGO",
    post: Profile3,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },
  {
    id: 5,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 15 MIN AGO",
    post: Profile4,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },
  {
    id: 6,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 15 MIN AGO",
    post: Profile5,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },
  {
    id: 7,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 15 MIN AGO",
    post: Profile6,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },
  {
    id: 8,
    user: "Romi Singh",
    profile_img: Profile,
    user_info: "India, 15 MIN AGO",
    post: Profile,
    liked_img_1: Profile1,
    liked_img_2: Profile2,
    liked_img_3: Profile4,
    liked_info: "Liked by Ankit and 345 other",
    caption: "Life is all about a race.",
    has_tag: "#lifestyle",
    comment: "view all 234 comments",
  },
];
